### ISSUE TITLE
著作権表示の表示

### ISSUE THREAD

**Issue by OR-11** [ysf-jk/ysf-jk.github.io#30]
蒼煌祭、ゲーム配布、ログのページの著作権表示が画面幅全体を締めていない。
ホーム、情報工学部についてのページの下の著作権表示の下に隙間がある

**Comment by OR-11** [comment]
~~スマートフォンからだと、ホーム、情報工学部について、蒼煌祭のページの著作権表示の~~ 全ページ?の著作権表示が画面端から離れている

**Comment by ysy-255** [comment]
スクショほしいです

**Comment by OR-11** [comment]
![スクリーンショット 2024-04-28 183438](https://github.com/ysf-jk/ysf-jk.github.io/assets/93813653/be6f12bd-e00a-48f2-9291-b93d56297766)
